sudo: true
deploy:
  provider: opsworks
  access_key_id: AKIAJW75BZSVGHFF4TNA
  secret_access_key:
    secure: v4yPrMH4PGohPekL+UvxqQfHnLaOy06ORVdWE1YhGuF0NshHgB+7mBjkM6DSkgAPYgIRQTQx3VMx6u8GAoRyLZnISSX/7o+boTmWaxwUwW9Rd6yeXaazV1LZ98PVDfnE+d9SkpcUnP8uZHmyAXGePT/pJidWmF4XV9PQoA5hsq04wLHEM75D1tKRCz0g06psd3bDzQXIE2/CuzPoXL0yPJ+AYomHHxWuzFdomeVeh9hhnqI5MIwFR2WnByB+u/CNeqK3y4c/rX3K1xuFsZyX8DonLhRn4f5Kav6GiTNkHu8t6oVa3ZVxx8tnkdOIZfanGHxh/FOjOZZjWNcDHtw7UzIRq+QRUxQGzMy9bLNwPEw8dqUzexwcVMy9ZfBYY60ZO7vCGfcc1oIX7CK4ig7OnMnzPmpniqZafDPQ8hqXWdayWCMtJJu7f+EXSpXnZx61s87SZBqRv3R4pMzAdjCNlH48/nDH1zOA7Hc0w57KNxVVCPOPkp1yopihJyZeSpSd1KjFa+s0wQ5jrmLJeV3XB9zd+BnQ/c2NJtjd43rQU9dJKoQnDll4OZOha+cPsTDl3yRS5hbq7sBwzg3IrZDBfK4jFgxfpQR3ThE79P/LGbKrnhc0LsTcxXZ02WtKXMdgq2IHgk6B/ead4XmCvGUsPx8wKQblJJtC0UNJjsiWaKE=
  app-id: bdemo