sudo: true
deploy:
  provider: opsworks
  access_key_id: AKIAJW75BZSVGHFF4TNA
  secret_access_key:
    secure: "ZTjfjsOX58yHxOMUz9Bvs0Hajqu+G6jOOBFbEFEAlXhEIRDcS6RH8Y0gdDMpfkHu0GICErleanvCax2k2AkfVZ7ISC/Nd/ABATp7SPUTVUZ1mRJB2UgC93Brh0qtuPjv8DBGTtFwG68aY8SfTja3xkLvl1Gh8QKsndqqOuA4Y+uMhAIjYBxYwCt6wRzg1gjW1LrPWv9kZegyLdLlVAIR+NSOBTJy2jkQnoaha5WWP005VvMwPjay0lharfS1t1qWUPhV7K6NGOW1lF5sNSSEQBHEF9BEP8h7+4o7aBB+hJvRB8xPUlwni2EjS57mT6Wpw30jX7Yva7r8hsG4DwECoujj2J+1/njgUH7ciwSgGCSMBJ/NiG06KQjnZUzrOvjBpkNFjA0NmmmbTlNZR1RgDFoBPwNXXuN+FI0vX/s0Tl0ZVovZ5rWM4NQ7UabhWfkd4akqYqi8EbqN0mJHVqwE562xeBvWldJ+W1Jf6e7AzTNTdLBc5btk4jOG+HdaDHFYUuKUWBwH4hJTlL09ly62bL5tmpj+SuYn9+Hk7IbVB6G5oG5HY/lIBXxxQq7/Mz2aSeJAoN2dyZxDOTx+1TmghxOxk7iNtO/VBckj7IcYPRJta3bJjlBsYBHhA74JSjlKAiKyoDzMs1Cr1TxYmBiE2n5wQV/ibOcIhMsnKzCPI9k="
  app-id: bdemo
