sudo: true
deploy:
  provider: opsworks
  access-key-id: AKIAJW75BZSVGHFF4TNA
  app-id: bdemo
  secret-access-key:
    secure: QeiV6wGGPAMshd8K0eI/J1t+UDZqdz/uJchaTPiCt7ZQmXaUda9n62zjI39PbTdW4/6W+qecgFod1sMz2wF9E9Xt9/eO1q33F0PDdGLpVhOUoYJbiD+JgXDSYGwcxPTB3N6ssqQYqV1iBNu1CBtVEcARXrQCYKSDeyAIl+cjgJH4aNvj1ryEs5GiKm6WSfa9pOuy4yb7pkucai2WCjXnQsh9AYgopmwK3+s5N4hG7No7br5YhjsyYzVdd76bMbW5rt3mLhLuguSqX8boX+j9lem+TQheDtKLdlSLC0E5f8d27YgSoHoSO0ZphCSoLW4PSGeQ22/9ICxPwvkiS9zuB0Q+ZfhVYacyYONlH4+4ohbPBD3iOhz+XGPjJesJLUc4i2ffHC+bjuf4rFYuarpg1A144wpFJq0IUMRw/jyHDJVnIjN/Xe7HVXpdqGPucd3S6+kWW8uHr20hjoaBdr8BYlWT1TbUsyiENfCWihWlubKvBK4aXiiUjB4wazaMFzHNWQEuoV8Gp8SrqT11Y+zXCJmWdn2Pdc1SpDfHgRnDuncamLfZ+cw00Cx8tbKCMhB8h1iEB1OF+R+7xg1+/BqsDlg8q0exu0gu6RxEEYH91JCBryQDXdjAUrFg64qmP7/vwQBXQgE9ILpnJL/Ouc29qQtY4e9K3XPzOpA71IdIzjE=
